#!/bin/bash
#
# Author: Pavlin Poličar <pavlin.g.p@gmail.com>
#
# This script is meant to be used with i3blocks. It parses the output of the
# "acpi" command to read the status of the battery and provide a nice visual
# interface through which the user can easily see the battery status.

# Get the battery number from the instance variable, default to 0.
battery_number="${BLOCK_INSTANCE:-0}"

colors=( "#AAAAAA" "#DE92A5" "#FF5983" )

acpi=$(acpi -b | grep "Battery $battery_number")
# Read the acpi battery state and set appropriate variables
if [[ $acpi =~ ^Battery[[:space:]][0-9]+:[[:space:]](Charging|Discharging),[[:space:]]([0-9]+)% ]]; then
  charging=$([[ "${BASH_REMATCH[1]}" = "Charging" ]] && echo true || echo false)
  percent=${BASH_REMATCH[2]}
else
  charging=true
  percent=100
fi

# Set battery and colors to be displayed later in the pango format
if ! $charging; then
  if (( $percent > 90 )); then
    battery=" $percent%" ; color="${colors[0]}"
  elif (( $percent > 70 )); then
    battery=" $percent%" ; color="${colors[0]}"
  elif (( $percent > 40 )); then
    battery=" $percent%" ; color="${colors[0]}"
  elif (( $percent > 20 )); then
    battery=" $percent%" ; color="${colors[1]}"
  else
    battery=" $percent%" ; color="${colors[2]}"
  fi
else
  battery=" $percent%"
  (( $percent < 100 )) && color="#2B63CC" || color="${colors[0]}"
fi

# Handle the left mouse click to display additional information
case $BLOCK_BUTTON in
  1)
    # If the battery is being discharged or is charging, display a different
    # message from when the battery is full
    if (( $percent < 100 )); then
      charging_text="Battery is <i>$(
        $charging && echo 'charging' || echo 'discharging'
      )</i> (currently at $percent%)"
      time_remaining=$(
        echo $acpi |
        awk -F'[,:\s]' '{
          if ($5 != '00') printf "<i>%d</i> hours ", $5 ;
          if ($5 != '00' && $5 != '00') printf "and " ;
          if ($6 != '00') printf "<i>%d</i> minutes ", $6 ;
          printf "remaining\n"
        }'
      )
    else
      charging_text="Battery is <i>full</i>"
    fi
    notify-send -u low "Battery status" "$charging_text\n$time_remaining"
    ;;
esac

echo $battery
echo $battery
echo $color
