#!/bin/bash

# Credentials
USERNAME="$(secret-tool lookup gmail username | tr -d '\n')"
PASSWORD="$(secret-tool lookup gmail api_key | tr -d '\n')"

case $BLOCK_BUTTON in
  1) i3-msg "exec chromium --new-tab www.gmail.com ; workspace 1:    " &>/dev/null ;;
esac

RESPONSE=$(curl -u "$USERNAME":"$PASSWORD" -s -i "https://mail.google.com/mail/feed/atom")

# If the response was not okay, due to connectivity or anything else, exit
if [ $(echo $RESPONSE | grep 'HTTP' | cut -d" " -f2) != "200" ]; then
  exit 0
fi

COUNT=$(echo $RESPONSE | grep -oPm1 "(?<=<fullcount>)[^<]+")

if [ "$COUNT" == "0" ]; then
  exit 0
fi

echo " $COUNT"
echo " $COUNT"
echo "#4586FF"
