#!/bin/bash

# Credentials
USERNAME="$(secret-tool lookup gmail username | tr -d '\n')"
PASSWORD="$(secret-tool lookup gmail api_key | tr -d '\n')"

case $BLOCK_BUTTON in
  1) i3-msg "exec chromium --new-tab www.gmail.com ; workspace 1:    " &>/dev/null ;;
esac

RESPONSE=$(curl -u "$USERNAME":"$PASSWORD" --silent "https://mail.google.com/mail/feed/atom")
# If no connection, don't display anything
[[ $? -ne 0 ]] && exit 0

COUNT=$(echo $RESPONSE |  grep -oPm1 "(?<=<fullcount>)[^<]+")

[[ "$COUNT" = "0" ]] && exit 0

echo " $COUNT"
echo " $COUNT"
echo "#4586FF"
