#!/bin/bash

# Use the device used for the default rotue.
INTERFACE="`ip route | awk '/^default/ { print $5 ; exit }'`"

if ! [ -e "/sys/class/net/${INTERFACE}/operstate" ] \
  || [ "`cat /sys/class/net/${INTERFACE}/operstate`" != "up" ]; then
    #echo "No network"
    #echo "No network"
    #echo "#666666"
    exit 0
fi

if [[ "$INTERFACE" =~ "wlp" ]]; then
  SSID="`iwgetid -r`"
  echo -n " $SSID"
elif [[ "$INTERFACE" =~ "enp" ]]; then
  echo -n ""
fi

# Handle a right click
AF="inet"
IPADDR="`ip addr show $INTERFACE | perl -n -e "/$AF ([^\/]+).*/ && print \$1 and exit"`"
case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac
