#!/bin/bash

# The case block must be in front of the checkupdates since that takes time
case $BLOCK_BUTTON in
  1) termite --class=Update --exec "zsh -c \"pacaur -Syu\"" ;;
esac

# Prefer pacaur over checkupdates since pacaur also lists outdated packages in
# the aur, unlike checkupdates.
UPDATES="$(( $(checkupdates | wc -l) + $(checkupdates-aur | wc -l) ))"
[[ "$UPDATES" = "0" ]] && exit 0

echo " $UPDATES"
echo " $UPDATES"
echo "#4586FF"
